name: "Deploy Azure Infrastructure"
description: "Deploys infra/main.bicep to Azure"

inputs:
  environment:
    description: The name of the environment to deploy to
    required: true

  azureCredentials:
    description: The credentials of the service principal created for GitHub Actions
    required: true

  targetRegion:
    description: Target region for Azure deployment 
    required: true

runs:
  using: composite
  steps:
    - name: Run Azure Login Action
      uses: azure/login@v1
      with:
        creds: ${{ inputs.azureCredentials }}

    - name: Run Azure ARM Deploy Action
      uses: azure/arm-deploy@v1
      with:
        scope: subscription
        region: ${{ inputs.targetRegion }}
        deploymentName: azure-infra-${{ inputs.environment }}-gha${{ github.run_number }}
        template: ./infra/main.bicep
        parameters: ./infra/parameters/deploy-azure-infra-parameters-${{ inputs.environment }}.json
