name: "Build and Test Project"

on: [push]

env:
  DOTNET_VERSION: 6.0.x # The .NET SDK version to use

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Run Unit Tests
        run: cd ./tests/PracticeFunctions.UnitTests && dotnet restore && dotnet build && dotnet test
