name: "Deploy Azure Infra to Dev Environment"

on:
  push:
    branches:
      - dev

jobs:
  call-deploy-app:
    uses: ./.github/workflows/deploy-app.yml
    with:
      environment: dev
      targetRegion: australiaeast
      dotnetVersion: "6.0.x"
      functionAppPackagePath: src/LearningLogFunctions
      functionAppName: fa-dev-bicep-practice
    secrets:
      azureCredentials: ${{ secrets.AZURE_CREDENTIALS }}
      functionAppPublishProfile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE_DEV }}
