name: "Deploy cicd-practice"

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

      targetRegion:
        required: true
        type: string

      dotnetVersion:
        required: true
        type: string

      functionAppPackagePath:
        required: true
        type: string

      functionAppName:
        required: true
        type: string

    secrets:
      azureCredentials:
        required: true

      functionAppPublishProfile:
        required: true

jobs:
  check-infra-env:
    runs-on: ubuntu-latest
    outputs:
      azure-credentials-exists: ${{ steps.azure-credentials-key.outputs.defined }}
    steps:
      - id: azure-credentials-key
        env:
          AZURE_CREDENTIALS_KEY: ${{ secrets.AZURE_CREDENTIALS }}
        if: "${{ env.AZURE_CREDENTIALS_KEY != '' }}"
        run: echo "::set-output name=defined::true"

  deploy-infra:
    needs: check-infra-env
    if: needs.check-infra-env.outputs.azure-credentials-exists == 'true'
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}

    steps:
      - name: Run Checkout GitHub Action
        uses: actions/checkout@v1

      - name: Deploy Azure Infra Action
        uses: ./.github/actions/deploy-azure-infra-action # Could refer to it with name/repo@tag I think
        with:
          environment: ${{ inputs.environment }}
          azureCredentials: ${{ secrets.azureCredentials }}
          targetRegion: ${{ inputs.targetRegion }}

  check-functions-env:
    runs-on: ubuntu-latest
    outputs:
      fa-publish-profile-exists: ${{ steps.fa-pubish-profile-key.outputs.defined }}
    
    steps:
      - id: fa-publish-profile-key-dev
        env:
          FA_PUBLISH_PROFILE_KEY_DEV: ${{ secrets.FUNCTIONAPP_PUBLISH_PROFILE_DEV }}
        if: "${{ env.FA_PUBLISH_PROFILE_KEY_DEV != '' && inputs.environment == 'dev'}}"
        run: echo "::set-output name=defined::true"

      - id: fa-publish-profile-key-prd
        env:
          FA_PUBLISH_PROFILE_KEY_PRD: ${{ secrets.FUNCTIONAPP_PUBLISH_PROFILE_PRD }}
        if: "${{ env.FA_PUBLISH_PROFILE_KEY_PRD != '' && inputs.environment == 'prd'}}"
        run: echo "::set-output name=defined::true"

  deploy-functions:
    needs: [deploy-infra, check-functions-env]
    if: needs.check-functions-env.outputs.fa-publish-profile-exists == 'true'
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
  
    steps:
      - name: Run Checkout GitHub Action
        uses: actions/checkout@v1

      - name: Deploy Azure Functions Action
        uses: ./.github/actions/deploy-azure-functions-action
        with:
          environment: ${{ inputs.environment }}
          dotnetVersion: ${{ inputs.dotnetVersion }}
          functionAppPackagePath: ${{ inputs.functionAppPackagePath }}
          functionAppName: ${{ inputs.functionAppName }}
          functionAppPublishProfile: ${{ secrets.functionAppPublishProfile }}
