name: "Deploy Environments"

on:
  push:
    branches:
      - dev
      - main
    paths-ignore:
      - '**.md'
      - '**.gitignore'
      - '**.gitattributes'
      - 'docs/**'
      - '.devcontainer/**'
      - 'tests/postman-collections**'

# TODO: Use https://github.com/marketplace/actions/set-environment-variables
# - Can create seperate .env files for dev and prd to reduce duplication of workflow call inputs

jobs:
  call-deploy-app-dev:
    if: github.ref_name == 'dev'
    uses: ./.github/workflows/deploy-app.yml
    with:
      environment: dev
      targetRegion: australiaeast
      dotnetVersion: "6.0.x"
      functionAppPackagePath: src/CiCdPracticeFunctions
      functionAppName: fa-dev-${{ github.event.repository.name }}
    secrets:
      azureCredentials: ${{ secrets.AZURE_CREDENTIALS }}
      functionAppPublishProfile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE_DEV }}

  call-deploy-app-prd:
    if: github.ref_name == 'main'
    uses: ./.github/workflows/deploy-app.yml
    with:
      environment: prd
      targetRegion: australiaeast
      dotnetVersion: "6.0.x"
      functionAppPackagePath: src/CiCdPracticeFunctions
      functionAppName: fa-prd-${{ github.event.repository.name }}
    secrets:
      azureCredentials: ${{ secrets.AZURE_CREDENTIALS }}
      functionAppPublishProfile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE_PRD }}
